feat(router): add support for request transform
BitGo/api-ts pull request #680
Opened 2024-02-16 03:34 UTC by jonball4

2024-02-16 16:38 UTC, stevenharrisBG requested changes
Please add jsdoc and update README
It really isn't at all clear how to use these changes without deep diving.

2024-02-21 12:45 UTC, manav-c commented on packages/typed-express-router/src/types.ts
> +type ApiMethodRequest<
```suggestion
type ApiRequest<
```

2024-02-21 12:45 UTC, manav-c commented on packages/typed-express-router/src/types.ts
> +type ApiMethodRequestType<
```suggestion
type ApiRequestType<
```

2024-02-21 13:06 UTC, manav-c commented on packages/typed-express-router/src/errors.ts
> +  res.status(500).end();
should update the default response error handler as well

2024-02-21 16:00 UTC, manav-c commented
Discussed with Jon on Slack - summary of my thoughts on these changes: These changes would make it clear to devs that there is a pattern of transforms that stems from thinking about the distinction between layers, like data and service -- but the transformation functions can easily be abused (just applying transformations in the route handler to meet the expectations of the transformation) or ignored completely. While these changes prompt devs think about transforms, I feel like the distinction pattern is more of a mindset that we need to cultivate within the team and am not sure if this PR helps with that specifically.

2024-02-21 16:20 UTC, closed without merging