Loosen the `is` check for `optionalized`
BitGo/api-ts pull request #737
Opened 2024-04-11 18:50 UTC by bitgopatmcl

The breaking change at https://github.com/BitGo/api-ts/commit/06eddbb5adfdf8b1638a4f0265ae25ec03264ba1 introduced a codec that bahaves like `partial` but strips explicit `undefined` properties when decoding and encoding. This is only used by `optionalized`, and it turns out it is broken at runtime, particularly in codebases that don't set `exactOptionalPropertyTypes`. It defaults to off, and much code treats "key not present" and "key set to `undefined`" interchangeably. Some combinators in `io-ts` such as `union` rely on `is` to determine which codec to use when encoding, so when an `optionalized` codec is used in a union, and is passed an object with defined-undefined properties to encode, it results in an exception. This change fixes that by loosening up the runtime `is` check. 

BREAKING CHANGE: explicit undefined properties are now accepted by `optionalized.is`

2024-04-11 19:02 UTC, andrew-scott-fischer requested changes

2024-04-11 19:02 UTC, andrew-scott-fischer commented on packages/io-ts-http/test/combinators.test.ts
> +  it.only('successfully encodes when in a union and passed explicitly undefined properties', () => {
```suggestion
  it('successfully encodes when in a union and passed explicitly undefined properties', () => {
```

2024-04-11 19:06 UTC, bitgopatmcl commented on packages/io-ts-http/test/combinators.test.ts
> +  it.only('successfully encodes when in a union and passed explicitly undefined properties', () => {
Fixed

2024-04-12 17:43 UTC, andrew-scott-fischer approved these changes

2024-04-12 17:44 UTC, merged