feature(openapi-generator): take and parse @example tags on JSDoc
BitGo/api-ts pull request #753
Opened 2024-04-30 16:31 UTC by ekorenblum-simtlix

DX-338

The OpenAPI generator module will now accept `@example` tags in the JSDoc, which will translate into OpenAPI examples. 
They may be used in the route definition to declare a response example, or in a schema definition to declare a schema usage example

## Usage: 

### Schema definition

Given the following JSDoc schema definition 
```javascript
/**
 * A variable with example
 * 
 * @example foo
 */
```

The resulting YAML declaration will be
```yaml
summary: A variable with example
tags:
  example:
    test: foo
```

### Endpoint definition

Given the following endpoint definition

```javascript
import * as t from 'io-ts';
import * as h from '@api-ts/io-ts-http';

/**
 * A simple route
 *
 * @operationId api.v1.test
 * @tag Test Routes
 * @example {
 *   "test": "bar"
 * }
 */
export const route = h.httpRoute({
  path: '/foo',
  method: 'GET',
  request: h.httpRequest({}),
  response: {
    200: {
      test: t.string
    }
  },
});
```

The resulting YAML declaration will be
```yaml
openapi: 3.0.3
info:
  title: Test
  version: 1.0.0
paths:
  "/foo":
    get:
      summary: A simple route
      operationId: api.v1.test
      tags:
      - Test Routes
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  test:
                    type: string
                required:
                - test
              example:
                test: bar
components:
  schemas: {}
```

2024-04-30 21:54 UTC, bitgopatmcl requested changes
Please re-word the commit message to use `feat(openapi-generator)` rather than `feature(openapi-generator)` since the latter won't be picked up by semantic-release.

2024-04-30 21:54 UTC, bitgopatmcl commented on packages/openapi-generator/src/jsdoc.ts
> +  tags?: Record<string, string> & { example?: unknown };
Technically this is unsound since `example` is a possible key of the record type so the final type should be the intersection of `string & unknown` which is just `string`

<img width="388" alt="image" src="https://github.com/BitGo/api-ts/assets/88669932/4a8d8c07-836f-4e48-ac61-5f287b23fd90">

However, the compiler does treat this in the intended manner of "example could be anything, all other properties are strings". If you want the type to be more accurate you could write `Record<Exclude<string, 'example'>, string> & { example?: unknown }` but it doesn't appear to make a difference in practice.

2024-04-30 21:54 UTC, bitgopatmcl commented on packages/openapi-generator/test/jsdoc.test.ts
> +     * }
Can we add a test for tags that come after a multi-line example?

2024-05-02 16:52 UTC, ekorenblum-simtlix commented on packages/openapi-generator/test/jsdoc.test.ts
> +     * }
Added!

2024-05-02 17:02 UTC, ekorenblum-simtlix commented on packages/openapi-generator/src/jsdoc.ts
> +  tags?: Record<string, string> & { example?: unknown };
Good catch! I changed it in the declaration as requested

2024-05-02 20:13 UTC, bitgopatmcl approved these changes

2024-05-02 20:14 UTC, bitgopatmcl approved these changes

2024-05-02 20:14 UTC, merged